# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: daa6b2dcffa46ac9d80a28c1b128d6595686cf2aa98b42ce7678fa66b2e09e49d24c1f83e869a9110f6f0d40faea209478e26f78992cae281ba4a2c21d019ab0

test:
  secret_key_base: b0c175ddd0907d78fe508eb290be7947cb4fc09c9261bc49bfd3bda13ef9873f63470fa5037cf9913760dc5b65d32fb3c43633e1086fe229dff459c841053046

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
